### ISSUE TITLE
IntegrityError when posting a post

### ISSUE THREAD

**Issue by vaethis** [brwr/thinkster-django-angular-boilerplate#21]
Received error: posts_post.author_id may not be NULL after trying to post.

**Comment by htercek** [comment]
Having also this error...
The problem is that somehow, preform_create newer get author so no create can be made... I'd look all over internet and nothing... pls. help !!!

**Comment by htercek** [comment]
Update of latest comment...
This error manifests when new post has to be made...

**Comment by htercek** [comment]
SOLVED !!!

the \post\views.py PostViewSet !!! If you copy/paste the code, make sure that perform_create is method of class PostViewSet ! Like this...
#------------------------------------------
class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.order_by('-created_at')
    serializer_class = PostSerializer

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:
            return (permissions.AllowAny(),)
        return (permissions.IsAuthenticated(), IsAuthorOfPost(),)

    **def perform_create(self, serializer):**
        instance = serializer.save(author=self.request.user)
        return super(PostViewSet, self).perform_create(serializer)
#------------------------------------------

**Comment by htercek** [comment]
without **  ** marks of course :)

**Comment by vaethis** [comment]
Thanks! Ill give it a shot.
