### ISSUE TITLE
Having issues with requirements.txt

### ISSUE THREAD

**Issue by NickysCousin** [brwr/thinkster-django-angular-boilerplate#28]
When I go to install requirements.txt, I get:

Collecting Django==1.7.1 (from -r requirements.txt (line 1))
  Using cached Django-1.7.1-py2.py3-none-any.whl
Collecting dj-database-url==0.3.0 (from -r requirements.txt (line 2))
  Using cached dj_database_url-0.3.0-py2.py3-none-any.whl
Collecting dj-static==0.0.6 (from -r requirements.txt (line 3))
  Using cached dj-static-0.0.6.tar.gz
Collecting django-appconf==0.6 (from -r requirements.txt (line 4))
  Using cached django-appconf-0.6.tar.gz
Collecting django-compressor==1.4 (from -r requirements.txt (line 5))
  Using cached django_compressor-1.4-py2.py3-none-any.whl
Collecting djangorestframework==3.0.0 (from -r requirements.txt (line 6))
  Using cached djangorestframework-3.0.0.tar.gz
Collecting drf-nested-routers==0.9.0 (from -r requirements.txt (line 7))
  Using cached drf-nested-routers-0.9.0.tar.gz
Collecting gunicorn==19.1.1 (from -r requirements.txt (line 8))
  Using cached gunicorn-19.1.1-py2.py3-none-any.whl
Collecting six==1.8.0 (from -r requirements.txt (line 9))
  Using cached six-1.8.0-py2.py3-none-any.whl
Collecting static3==0.5.1 (from -r requirements.txt (line 10))
  Using cached static3-0.5.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 11))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ANDYRE~1\AppData\Local\Temp\pip-build-1j_t8fsg\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\ANDYRE~1\AppData\Local\Temp\pip-build-1j_t8fsg\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by mcscruf61** [comment]
Tutorial is built for Python 2.7.  You can install your desired version of python in your virtual environment using the following:
```
$ mkvirtualenv thinkster-djangular --python=python2.7
```
