### ISSUE TITLE
Stuck on step 2: mkvirtualenv - not found

### ISSUE THREAD

**Issue by rwielinga** [brwr/thinkster-django-angular-boilerplate#30]
Hi Thanks for this tutorial.

I am having issues setting up my environment. (using Python 3.6)
After installing virtualenv and virtualenvwrapped I don't have the command mkvirtualenv available.

Do you know how i can still proceed?

**Comment by wedwardbeck** [comment]
I had the same issue on another project - I skipped the virtualenvwrapped and just used the virtualenv.   

$ virtualenv ENV (replace ENV with your own dir for the virtual env)

then follow [this link ](https://virtualenv.pypa.io/en/stable/userguide/) to run it 

I never had success using virtualenvwrapped (On Windows) so just skipped it altogether.

**Comment by brwr** [comment]
Alternatively, check out `pyenv`: https://github.com/pyenv/pyenv.

Closing for now as there are two good solutions here. Feel free to open another issue if needed.
